export interface TemplateConfigRecord {
  id: string;
  name: string;
  title: string;
  footer: string;
  showStatistics: boolean;
  showExecutions: boolean;
  showPreconditions: boolean;
  showSteps: boolean;
  showApprovals: boolean;
  showContext: boolean;
  failedOnly: boolean;
  active: boolean;
}

export const TEMPLATE_CONFIGS: TemplateConfigRecord[] = [
  {
    id: 'default',
    name: 'Default Template',
    title: 'Project Quality Report',
    footer: 'Generated by DocGen Mock Pipeline',
    showStatistics: true,
    showExecutions: true,
    showPreconditions: true,
    showSteps: true,
    showApprovals: true,
    showContext: true,
    failedOnly: false,
    active: true,
  },
  {
    id: 'compact',
    name: 'Compact Template',
    title: 'Compact Test Summary',
    footer: 'Internal Use Only',
    showStatistics: true,
    showExecutions: false,
    showPreconditions: false,
    showSteps: true,
    showApprovals: false,
    showContext: true,
    failedOnly: false,
    active: false,
  },
  {
    id: 'failure-focus',
    name: 'Failure Focus Template',
    title: 'Failure Investigation Report',
    footer: 'Action Required: Review Failed Tests',
    showStatistics: true,
    showExecutions: true,
    showPreconditions: true,
    showSteps: true,
    showApprovals: true,
    showContext: true,
    failedOnly: true,
    active: false,
  },
];
